### ISSUE TITLE
How to change the size of the notepad area

### ISSUE THREAD

**Issue by laststoneleft** [svoekino/plain-text-2#1]
Very nice thing you did. Congrats!
Now, how to change the size of the notepad area?
Didn't find also how to change the font maybe.

**Comment by laststoneleft** [comment]
Please add firefox shortcut for open

**Comment by laststoneleft** [comment]
Please make it possible to activate on mouse click. Thank you

**Comment by svoekino** [comment]
The features of resizing notepad area with the mouse and and keyboard shortcuts will be added to the new release. 

For now, you can change the size using the bullet before the title of the note.

**Comment by svoekino** [comment]
In the new version "2.4.0", are available keyboard shortcuts to open notepad (Ctrl+shift+U by default) and change the size of the notepad area on cursor movement.

More advanced settings (fonts changing , window size, etc.) will appear in the next release. 

Thank's for your suggestions.
